name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  continuous-deployment-Application:
    runs-on: ubuntu-latest
    needs: [ continuous-integration ]
    steps: 
    - uses: actions/checkout@v3
    - name: Deployment Application to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.APPS_HOSTNAME }}
        username: ${{ secrets.APPS_USERNAME }}
        password: ${{ secrets.APPS_PASSWORD }}
        port: ${{ secrets.APPS_PORT }}
        script: cd /root/go/src/TamaskaPublicLighting && systemctl stop tamaska-app && git pull && systemctl start tamaska-app
  continuos-deployment-Database:
    runs-on: ubuntu-latest
    needs: [ continuous-deployment-Application ]
    steps:
    - uses: actions/checkout@v3
    - name: Deployment Database to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DB_HOSTNAME }}
        username: ${{ secrets.DB_USERNAME }}
        password: ${{ secrets.DB_PASSWORD }}
        port: ${{ secrets.DB_PORT }}
        script:  cd /root/TamaskaPublicLighting/database && git pull && mysql -u root --password=riz123tmk -D tamaskapubliclight -e "DROP DATABASE tamaskapubliclight" && mysql -u root --password=riz123tmk -e "CREATE DATABASE tamaskapubliclight" && mysql -u root --password=riz123tmk tamaskapubliclight < tamaskapubliclight.sql